Fix the expected output of ec2-delete-snapshot.
Test Plan:
None -- I don't want to go around deleting snapshots!  But the error
message I got was this:
---
RuntimeError: Unexpected output from ec2-delete-snapshot: "SNAPSHOT     snap-10b71d50
"
---
so it's plausible the missing newline was the problem.

Reviewers: benkomalo, alpert

Reviewed By: benkomalo

Differential Revision: http://phabricator.khanacademy.org/D2041